### ISSUE TITLE
Minor usability issues

### ISSUE THREAD

**Issue by hannahbast** [ad-freiburg/pdfact#4]
I just used it and found some minor usability issues:

1. It's unfortunate that one has to be in the install directory to call the script. Isn't there a better solution for this?

2. With each call, I got the warnings shown in [1] below

3. In the README.md the "Optional Arguments" box is so wide that one has to scroll back and forth horizontally to read the lines.

4. It is not clear what the --unit option does before applying it. A bit more explanation would be good.

5. How are the semantic roles determined? For example, I ran it on a PDF with various headers, but it didn't extract any headers. It would be good to understand, why in prinicple that happened.

[1] Warnings at the beginning when calling ./pdfact <anything>

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.assistedinject.FactoryProvider2$MethodHandleWrapper (file:/local/data/bast/completesearch/applications/enquete/documents/pdfact/bin/pdfact.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of com.google.inject.assistedinject.FactoryProvider2$MethodHandleWrapper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by hannahbast** [comment]
I just pulled the latest version and the warnings are still there

**Comment by ckorzen** [comment]
Yeah, I noticed this as well. I assumed that my last commit would fix the problem, but it did not (that's why the issue is still open). The warnings are caused by the Google Guice library and are [a common issue](https://github.com/google/guice/issues/1133) which isn't fixed yet. The fix mentioned in [this post](https://github.com/google/guice/issues/1133#issuecomment-718026293) doesn't work for me.

One option to fix the issue would be to eliminate Google Guice from our project. But that would mean 1-2 days of work.

**Comment by ckorzen** [comment]
Fixed.
